version: '3.8'

services:
  postgres:
    image: postgres:18-alpine
    container_name: home-library-db
    restart: unless-stopped # autorestart
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - home-library-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: home-library-app
    restart: unless-stopped
    ports:
      - '${PORT}:${PORT}'
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
      CRYPT_SALT: ${CRYPT_SALT}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_SECRET_REFRESH_KEY: ${JWT_SECRET_REFRESH_KEY}
      TOKEN_EXPIRE_TIME: ${TOKEN_EXPIRE_TIME}
      TOKEN_REFRESH_EXPIRE_TIME: ${TOKEN_REFRESH_EXPIRE_TIME}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./src:/app/src # Hot reload
      - /app/node_modules
    networks:
      - home-library-network

volumes:
  postgres_data:

networks:
  home-library-network:
    driver: bridge
